

== Thoughts / Notes

This is lowkey a hard question to answer. I guess everyone wants to know, or doesn't, who you are. They also want the easiest answer; They want the most comfortable one. It is really hard to potray who I am because in some essence I am only me to me. To everyone else I am a different "representation" or facet of myself. Even with our closest loved ones, it's still only a surface of the whole volume if you will. The crazy part is the volume is always changing and the surface doesn't always change to reflect that. So when you have to tell someone who you are it's kind of hard beacuse it have to construct this surface they see you as by only giving them hints. So when it comes to like job applications, class projects, biographys, its kind of hard to boil all of that down into one sheet of paper. People write books on their lives, and even then it usually isn't enough to capture even a small bit of this person experience and internal sense of self. Often when we write these papers it's a lot of external factors of our identity; "I am black; I am a person; Here are my experiences." I feel like in essence to ask someone to tell them who you are is kind of a paradoxical question because there is no way to translate such a inifinite dimensional concept into something as low dimensional as words. Even if we could somehow manage to capture every aspect of a person into words, or some other medium, the moment it was recorded it would instantly be old information. The mere act of "capturing a person in a bottle" will change the person you are capturing. It almost reminds me of heisenburg's uncertantity principle. The more you know about one aspect of this thing the less you know about another (obviously this is a massive over-simplification, but I think it operates as a good metaphor for the idea I am trying to convey). I think it might be fun to try and write the poem around that idea. That culture, people, experiences are so infinetly complex. To ask someone to "tell you about themselves or their culture" is asking them to categorize them self for your digestion. Of course asking everyone to form their own opions of people unassisted is really hard. We sadly don't have time or resources to experience everyone meet on a daily basis without trying to perform this compression of thier person. I don't think there is anything inherantly wrong with doing this, but not recognizing that you are doing it I think is the real moral failing. For example in this class we talked about how people were minimized into the category "Hispanic", which is such a low dimensional description of such a large set of people, it is laughable.

I think the reason I think about all of this is because when we we are asked to write a people like this it is so hard to capture all of who I am in peice of written text, which also needs to be so small. If I say I love math, most form an idea of me that is "A person who likes math". For some this is a nerd, or some this is someone who loves to learn, etc... If I say, "I am trans", then their perception becomes "A trans person" of me, and then it completely changes how they interact and form opinions of a person. If I say I love programming, then the perception can change again. It's hard because a lot of these categories also tend to carry very heavy, very differing opinions of these people. For example the math, or trans one; I love these things, but I find it is almost hard to say because of the attached opinions. A lot of the time it is better to omit it and then introduce those topics over time because then it allows people to form a more accurate representation of who I am. I love math, but I love people. I love culture. I love art. I love music. I have ADHD, I like many things, but I love working on projects usually of some type, which wouldn't fit the normal description. I yap; Sometimes I don't. Sometimes I mask; SOmetimes I can't; Sometime's I choose not to.

I think that is the direction I want to take this poem with. Answer the question quickly, but then interrogate what it means to even answer this question.
